# Generated by Django 3.1.2 on 2021-02-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoTaskList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitems',
            old_name='makeas',
            new_name='markeas',
        ),
    ]
